!pip install -U gym gym[other] tensorflow keras autorom gym[accept-rom-license] gym[atari] torch

In [2]:
import numpy as np
from collections import deque
import gym


In [2]:
env = gym.make("Breakout-v4", obs_type='grayscale', render_mode='rgb_array', full_action_space=False, frameskip=4)
env = gym.wrappers.AtariPreprocessing(env=env, frame_skip=1, terminal_on_life_loss=True)
env = gym.wrappers.FrameStack(env=env, num_stack=4)
# env = gym.wrappers.RecordVideo(env, 'videos', episode_trigger= lambda x : x % 30 == 0)


A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
/home/meliioko/dqn-breakout/.venv/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:31: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (210, 160)
  logger.warn(


In [2]:
import matplotlib.pyplot as plt
import random
def print_image(im):
    fig, axs = plt.subplots(1, 4, figsize=(50,50))
    for i in range(4):
        axs[i].imshow(im[i])
        fig.show()
state = env.reset()[0]
print_image(state)
for _ in range(20):
    state, _,_,_,_, = env.step(random.randrange(4))
    print_image(state)


NameError: name 'env' is not defined

In [4]:
import torch
from dqn import DQN, preprocess_state

device = torch.device('cuda')
env = gym.make("Breakout-v4", obs_type='grayscale', render_mode='rgb_array', full_action_space=False, frameskip=4)
env = gym.wrappers.AtariPreprocessing(env=env, frame_skip=1, terminal_on_life_loss=True)
env = gym.wrappers.FrameStack(env=env, num_stack=4)
env = gym.wrappers.RecordVideo(env, 'test_videos',)

device = torch.device("cuda")
Q = DQN(env.action_space.n)
Q.load_state_dict(torch.load('Q.pt'))
Q.to(device)

state = preprocess_state(env.reset()[0], device)
done = False
total_reward = 0
state, reward, done, _, b = env.step(action=1)


state = preprocess_state(state, device)
total_reward += reward
while not done:
    with torch.no_grad():  # No need to track gradients here
        act_values = Q(state)
        print(act_values.cpu().numpy())
        action = act_values.max(1)[1].item()  # Choose the action with the highest Q-value
    
    state, reward, done, _, b = env.step(action=action)
    total_reward += reward
    state = preprocess_state(state=state, device=device)
print(total_reward)


/home/meliioko/dqn-breakout/.venv/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:31: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (210, 160)
  logger.warn(


Moviepy - Building video /home/meliioko/dqn-breakout/test_videos/rl-video-episode-0.mp4.
Moviepy - Writing video /home/meliioko/dqn-breakout/test_videos/rl-video-episode-0.mp4



Moviepy - Done !
Moviepy - video ready /home/meliioko/dqn-breakout/test_videos/rl-video-episode-0.mp4
[[17.011728 16.96551  16.854515 17.007347]]
[[16.365253 16.258041 16.246859 16.332537]]
[[16.80309  16.738224 16.661089 16.809702]]
[[16.029547 15.990257 16.071182 16.000246]]
[[15.134556  15.127729  15.0794525 15.131811 ]]
[[15.072222 15.024788 15.021516 15.024591]]
[[16.266367 16.18205  16.222065 16.206612]]
[[16.518595 16.473774 16.32105  16.544155]]
[[16.202188 16.158741 15.944371 16.22726 ]]
[[17.43644  17.320862 17.285643 17.423742]]
[[16.716991 16.65512  16.625513 16.69894 ]]
[[16.049534 15.956877 14.806406 16.055841]]
[[16.122025 16.111645 12.37368  16.243706]]
[[17.019234 16.97119  13.392449 17.021338]]
[[17.08074  17.169413 13.603015 17.140343]]
[[18.430847 18.411596 18.372934 18.39976 ]]
[[18.603514 18.570137 18.54765  18.583323]]
[[18.393744 18.299746 18.461525 18.351578]]
[[19.583952 19.532173 19.470974 19.582764]]
[[19.119184 19.063114 19.001612 19.053637]]
[[19.410007 19

/home/meliioko/dqn-breakout/.venv/lib/python3.10/site-packages/gym/wrappers/record_video.py:75: UserWarning: WARN: Overwriting existing videos at /home/meliioko/dqn-breakout/test_videos folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/home/meliioko/dqn-breakout/.venv/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
/home/meliioko/dqn-breakout/.venv/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:289: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


[[18.51095  18.437487 18.362356 18.407558]]
[[17.525246 17.48755  17.462334 17.463709]]
[[16.186563 16.166151 16.14055  16.14856 ]]
[[16.598602 16.571636 16.568834 16.571383]]
[[14.9925995 14.982754  14.971971  14.951471 ]]
[[14.676359 14.655222 14.627783 14.666627]]
[[14.830045 14.800203 14.783987 14.784284]]
[[15.217864 15.183256 15.134536 15.203391]]
[[15.580303 15.554995 15.525263 15.561391]]
[[14.713568 14.681774 14.665609 14.698968]]
[[13.406845 13.382219 13.369129 13.405466]]
[[13.65504  13.663553 13.57749  13.662777]]
[[14.611455 14.624565 14.511512 14.629607]]
[[14.4644375 14.459476  14.402414  14.4651785]]
[[15.143334 15.139339 15.092811 15.11973 ]]
[[13.569678 13.570147 13.459333 13.547005]]
[[13.211041 13.215399 13.169411 13.213616]]
[[13.469889 13.452082 13.503    13.439862]]
[[12.187555 12.167011 12.158967 12.127902]]
[[11.671526 11.65556  11.641275 11.636643]]
[[12.292821 12.262476 12.323512 12.201628]]
[[12.181781 12.264624 12.086114 11.552664]]
[[12.10874   12.211243  

Moviepy - Done !
Moviepy - video ready /home/meliioko/dqn-breakout/test_videos/rl-video-episode-0.mp4
14.0
